=== Mouadouakil/Students-Marks-System-Xml-Java/STUDENTS/Students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="Students">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Student" minOccurs="1" maxOccurs="unbounded">   
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ID" type="xs:integer"/>
                            <xs:element name="CNE" type="xs:string"/>
                            <xs:element name="DateofBirth" type="xs:date"/>
                            <xs:element name="FirstName" minOccurs="1" maxOccurs="unbounded" >
                              <xs:simpleType>
                                  <xs:restriction base="xs:string">
                                      <xs:pattern value="([a-zA-z])*"/>
                                  </xs:restriction>
                              </xs:simpleType>  
                            </xs:element>
                           
                            <xs:element name="LastName" minOccurs="1" maxOccurs="unbounded">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="([a-zA-z])*"/>
                                    </xs:restriction>
                                </xs:simpleType>  
                            </xs:element>
                            
                            <xs:element name="ClasseName" type="xs:string"/>
                            <xs:element name="Phone" type="xs:string"/>
                            <xs:element name="Email" type="xs:string"/>
                       </xs:sequence>
                        <xs:attribute name="id" type="xs:positiveInteger" use="optional"/>
                    </xs:complexType> 
                </xs:element>
            </xs:sequence>
 
        </xs:complexType>
    </xs:element>   
</xs:schema>

=== Mouadouakil/Students-Marks-System-Xml-Java/STUDENTS/Students_G3EI3.xml
<?xml version="1.0" encoding="UTF-8"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Students.xsd">
<Student>
<ID>1</ID>
<CNE>16270519</CNE>
<DateofBirth>1997-03-31</DateofBirth>
<FirstName>Henson</FirstName>
<LastName>Black</LastName>
<ClasseName>G3EI3</ClasseName>
<Phone>03 94 02 54 66</Phone>
<Email>In.condimentum.Donec@congueturpisIn.org</Email>
</Student>
<Student>
<ID>2</ID>
<CNE>16260520</CNE>
<DateofBirth>1997-11-23</DateofBirth>
<FirstName>Ballard</FirstName>
<LastName>Curtis</LastName>
<ClasseName>G3EI3</ClasseName>
<Phone>07 39 78 43 24</Phone>
<Email>pretium.neque@vitaevelitegestas.com</Email>
</Student>
<Student>
<ID>3</ID>
<CNE>16221030</CNE>
<DateofBirth>1997-09-22</DateofBirth>
<FirstName>Holcomb</FirstName>
<LastName>Fox</LastName>
<ClasseName>G3EI3</ClasseName>
<Phone>06 69 98 76 69</Phone>
<Email>sapien@metusAliquamerat.com</Email>
</Student>
<Student>
<ID>4</ID>
<CNE>16880313</CNE>
<DateofBirth>1997-06-22</DateofBirth>
<FirstName>Fuller</FirstName>
<LastName>Guthrie</LastName>
<ClasseName>G3EI3</ClasseName>
<Phone>04 23 10 99 79</Phone>
<Email>Nunc.pulvinar.arcu@Crasloremlorem.co.uk</Email>
</Student>
<Student>
<ID>5</ID>
<CNE>16561026</CNE>
<DateofBirth>1997-06-10</DateofBirth>
<FirstName>Beard</FirstName>
<LastName>Holloway</LastName>
<ClasseName>G3EI3</ClasseName>
<Phone>03 33 26 13 38</Phone>
<Email>pede.ultrices.a@Maurismolestie.edu</Email>
</Student>
<Student>
<ID>6</ID>
<CNE>16690512</CNE>
<DateofBirth>1997-10-02</DateofBirth>
<FirstName>Mcmillan</FirstName>
<LastName>George</LastName>
<ClasseName>G3EI3</ClasseName>
<Phone>02 20 86 75 67</Phone>
<Email>in.consequat.enim@est.com</Email>
</Student>
<Student>
<ID>7</ID>
<CNE>16590519</CNE>
<DateofBirth>1997-10-13</DateofBirth>
<FirstName>Knapp</FirstName>
<LastName>Ortiz</LastName>
<ClasseName>G3EI3</ClasseName>
<Phone>09 45 26 18 08</Phone>
<Email>Proin.dolor@tellusNunclectus.ca</Email>
</Student>
<Student>
<ID>8</ID>
<CNE>16320103</CNE>
<DateofBirth>1997-11-14</DateofBirth>
<FirstName>Washington</FirstName>
<LastName>Benjamin</LastName>
<ClasseName>G3EI3</ClasseName>
<Phone>09 36 77 95 15</Phone>
<Email>quis.accumsan@purusDuis.org</Email>
</Student>
<Student>
<ID>9</ID>
<CNE>16171118</CNE>
<DateofBirth>1997-06-08</DateofBirth>
<FirstName>Cabrera</FirstName>
<LastName>Ross</LastName>
<ClasseName>G3EI3</ClasseName>
<Phone>09 60 01 73 60</Phone>
<Email>Etiam@vestibulumMaurismagna.ca</Email>
</Student>
<Student>
<ID>10</ID>
<CNE>16020307</CNE>
<DateofBirth>1997-06-05</DateofBirth>
<FirstName>Brennan</FirstName>
<LastName>York</LastName>
<ClasseName>G3EI3</ClasseName>
<Phone>04 42 18 04 41</Phone>
<Email>mi.lacinia.mattis@lacus.co.uk</Email>
</Student>
<Student>
<ID>11</ID>
<CNE>16871112</CNE>
<DateofBirth>1997-11-14</DateofBirth>
<FirstName>Byrd</FirstName>
<LastName>Mendoza</LastName>
<ClasseName>G3EI3</ClasseName>
<Phone>03 05 21 68 60</Phone>
<Email>urna.et@anteblanditviverra.ca</Email>
</Student>
<Student>
<ID>12</ID>
<CNE>16301010</CNE>
<DateofBirth>1997-10-18</DateofBirth>
<FirstName>Rosa</FirstName>
<LastName>Oneal</LastName>
<ClasseName>G3EI3</ClasseName>
<Phone>05 66 61 50 52</Phone>
<Email>ornare.placerat.orci@liberoInteger.ca</Email>
</Student>
<Student>
<ID>13</ID>
<CNE>16530228</CNE>
<DateofBirth>1997-07-28</DateofBirth>
<FirstName>Cain</FirstName>
<LastName>Ingram</LastName>
<ClasseName>G3EI3</ClasseName>
<Phone>07 52 82 52 74</Phone>
<Email>elit@condimentumDonecat.ca</Email>
</Student>
<Student>
<ID>14</ID>
<CNE>16140326</CNE>
<DateofBirth>1997-06-16</DateofBirth>
<FirstName>Graves</FirstName>
<LastName>Justice</LastName>
<ClasseName>G3EI3</ClasseName>
<Phone>06 81 67 87 51</Phone>
<Email>mauris@anunc.com</Email>
</Student>
<Student>
<ID>15</ID>
<CNE>16400928</CNE>
<DateofBirth>1997-11-12</DateofBirth>
<FirstName>Greer</FirstName>
<LastName>Guerrero</LastName>
<ClasseName>G3EI3</ClasseName>
<Phone>08 38 69 72 39</Phone>
<Email>Phasellus@nisiAenean.com</Email>
</Student>
<Student>
<ID>16</ID>
<CNE>16450723</CNE>
<DateofBirth>1997-05-17</DateofBirth>
<FirstName>Britt</FirstName>
<LastName>Cummings</LastName>
<ClasseName>G3EI3</ClasseName>
<Phone>05 53 11 64 65</Phone>
<Email>tempus@malesuadaut.edu</Email>
</Student>
<Student>
<ID>17</ID>
<CNE>16220519</CNE>
<DateofBirth>1997-10-20</DateofBirth>
<FirstName>Cardenas</FirstName>
<LastName>William</LastName>
<ClasseName>G3EI3</ClasseName>
<Phone>08 03 62 30 91</Phone>
<Email>egestas@diamSed.co.uk</Email>
</Student>
<Student>
<ID>18</ID>
<CNE>16831227</CNE>
<DateofBirth>1997-11-02</DateofBirth>
<FirstName>Chambers</FirstName>
<LastName>Fields</LastName>
<ClasseName>G3EI3</ClasseName>
<Phone>07 26 09 29 06</Phone>
<Email>ridiculus@eudui.edu</Email>
</Student>
<Student>
<ID>19</ID>
<CNE>16020130</CNE>
<DateofBirth>1997-10-18</DateofBirth>
<FirstName>Hull</FirstName>
<LastName>Jimenez</LastName>
<ClasseName>G3EI3</ClasseName>
<Phone>03 44 39 02 48</Phone>
<Email>Duis.at.lacus@euligulaAenean.ca</Email>
</Student>
<Student>
<ID>20</ID>
<CNE>16690410</CNE>
<DateofBirth>1997-04-17</DateofBirth>
<FirstName>Martinez</FirstName>
<LastName>Newman</LastName>
<ClasseName>G3EI3</ClasseName>
<Phone>05 05 23 89 96</Phone>
<Email>vitae.erat@libero.net</Email>
</Student>
<Student>
<ID>21</ID>
<CNE>16760310</CNE>
<DateofBirth>1997-10-29</DateofBirth>
<FirstName>Melton</FirstName>
<LastName>Fernandez</LastName>
<ClasseName>G3EI3</ClasseName>
<Phone>09 70 06 91 76</Phone>
<Email>Donec.feugiat@Vivamusmolestiedapibus.net</Email>
</Student>
</Students>

=== Mouadouakil/Students-Marks-System-Xml-Java/STUDENTS/Students_GSEA2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Students.xsd">
<Student>
<ID>1</ID>
<CNE>217976651</CNE>
<DateofBirth>1998-11-02</DateofBirth>
<FirstName>Cunningham</FirstName>
<LastName>Walls</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>01 98 15 38 15</Phone>
<Email>eu.dui@fames.com</Email>
</Student>
<Student>
<ID>2</ID>
<CNE>168490388</CNE>
<DateofBirth>1998-08-14</DateofBirth>
<FirstName>Walter</FirstName>
<LastName>Davis</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>03 62 33 36 36</Phone>
<Email>ultricies.ligula@lobortisquis.edu</Email>
</Student>
<Student>
<ID>3</ID>
<CNE>193806536</CNE>
<DateofBirth>1998-08-23</DateofBirth>
<FirstName>Howe</FirstName>
<LastName>Hudson</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>09 26 07 62 45</Phone>
<Email>ipsum.nunc.id@semperauctor.co.uk</Email>
</Student>
<Student>
<ID>4</ID>
<CNE>151840168</CNE>
<DateofBirth>1998-03-15</DateofBirth>
<FirstName>Chan</FirstName>
<LastName>Wallace</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>06 79 51 33 14</Phone>
<Email>Donec@euarcu.net</Email>
</Student>
<Student>
<ID>5</ID>
<CNE>222621514</CNE>
<DateofBirth>1998-03-28</DateofBirth>
<FirstName>Herring</FirstName>
<LastName>Booker</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>04 20 70 22 80</Phone>
<Email>cursus.et.magna@Duisatlacus.co.uk</Email>
</Student>
<Student>
<ID>6</ID>
<CNE>174516619</CNE>
<DateofBirth>1998-10-24</DateofBirth>
<FirstName>Whitfield</FirstName>
<LastName>Harvey</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>08 21 70 73 31</Phone>
<Email>Suspendisse@ut.edu</Email>
</Student>
<Student>
<ID>7</ID>
<CNE>227863392</CNE>
<DateofBirth>1998-09-18</DateofBirth>
<FirstName>Sellers</FirstName>
<LastName>Sutton</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>09 76 13 84 32</Phone>
<Email>feugiat@quama.net</Email>
</Student>
<Student>
<ID>8</ID>
<CNE>208243362</CNE>
<DateofBirth>1998-09-25</DateofBirth>
<FirstName>Shaw</FirstName>
<LastName>Hewitt</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>05 34 42 26 93</Phone>
<Email>Phasellus@blanditNam.com</Email>
</Student>
<Student>
<ID>9</ID>
<CNE>294939896</CNE>
<DateofBirth>1998-07-12</DateofBirth>
<FirstName>Simpson</FirstName>
<LastName>Kemp</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>05 20 10 92 12</Phone>
<Email>massa.Quisque.porttitor@velarcu.edu</Email>
</Student>
<Student>
<ID>10</ID>
<CNE>221874850</CNE>
<DateofBirth>1998-08-14</DateofBirth>
<FirstName>Mooney</FirstName>
<LastName>Gutierrez</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>03 70 62 81 63</Phone>
<Email>orci@eleifendegestasSed.com</Email>
</Student>
<Student>
<ID>11</ID>
<CNE>262115203</CNE>
<DateofBirth>1998-08-18</DateofBirth>
<FirstName>Moody</FirstName>
<LastName>Gates</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>08 80 67 41 59</Phone>
<Email>vulputate.velit.eu@auctor.com</Email>
</Student>
<Student>
<ID>12</ID>
<CNE>246484900</CNE>
<DateofBirth>1998-10-14</DateofBirth>
<FirstName>Gray</FirstName>
<LastName>Atkinson</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>08 21 19 22 09</Phone>
<Email>non.egestas@sedduiFusce.edu</Email>
</Student>
<Student>
<ID>13</ID>
<CNE>227958143</CNE>
<DateofBirth>1998-12-31</DateofBirth>
<FirstName>Freeman</FirstName>
<LastName>Cross</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>07 66 80 80 12</Phone>
<Email>nec.tempus.mauris@dolor.org</Email>
</Student>
<Student>
<ID>14</ID>
<CNE>258112876</CNE>
<DateofBirth>1998-12-27</DateofBirth>
<FirstName>Parsons</FirstName>
<LastName>Woodward</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>04 89 17 64 92</Phone>
<Email>Donec.at@pulvinararcu.com</Email>
</Student>
<Student>
<ID>15</ID>
<CNE>196721747</CNE>
<DateofBirth>1998-11-18</DateofBirth>
<FirstName>Ingram</FirstName>
<LastName>Hart</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>07 70 53 02 48</Phone>
<Email>vulputate.nisi@In.net</Email>
</Student>
<Student>
<ID>16</ID>
<CNE>280556550</CNE>
<DateofBirth>1998-03-03</DateofBirth>
<FirstName>Oneill</FirstName>
<LastName>Irwin</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>04 12 73 02 66</Phone>
<Email>eleifend@mollislectuspede.com</Email>
</Student>
<Student>
<ID>17</ID>
<CNE>259743180</CNE>
<DateofBirth>1998-12-24</DateofBirth>
<FirstName>Kerr</FirstName>
<LastName>Anthony</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>05 91 51 99 17</Phone>
<Email>posuere.enim.nisl@nonluctussit.com</Email>
</Student>
<Student>
<ID>18</ID>
<CNE>186435843</CNE>
<DateofBirth>1998-02-03</DateofBirth>
<FirstName>Bowen</FirstName>
<LastName>Michael</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>06 25 62 87 16</Phone>
<Email>ante.Nunc@lorem.com</Email>
</Student>
<Student>
<ID>19</ID>
<CNE>183147600</CNE>
<DateofBirth>1998-07-11</DateofBirth>
<FirstName>Garrison</FirstName>
<LastName>Welch</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>09 56 64 06 91</Phone>
<Email>Mauris.non@miDuis.edu</Email>
</Student>
<Student>
<ID>20</ID>
<CNE>265715842</CNE>
<DateofBirth>1998-04-20</DateofBirth>
<FirstName>Phillips</FirstName>
<LastName>Norman</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>08 71 20 95 09</Phone>
<Email>rhoncus@estvitaesodales.edu</Email>
</Student>
<Student>
<ID>21</ID>
<CNE>187969093</CNE>
<DateofBirth>1998-09-11</DateofBirth>
<FirstName>Carver</FirstName>
<LastName>Calhoun</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>04 56 71 89 00</Phone>
<Email>lorem.semper@vitaesemperegestas.edu</Email>
</Student>
<Student>
<ID>22</ID>
<CNE>248552948</CNE>
<DateofBirth>1998-06-06</DateofBirth>
<FirstName>Hampton</FirstName>
<LastName>Dejesus</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>06 97 28 41 82</Phone>
<Email>erat@Phasellus.co.uk</Email>
</Student>
<Student>
<ID>23</ID>
<CNE>152814419</CNE>
<DateofBirth>1998-05-16</DateofBirth>
<FirstName>Buckley</FirstName>
<LastName>Holder</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>02 79 05 38 30</Phone>
<Email>imperdiet.dictum@nulla.net</Email>
</Student>
<Student>
<ID>24</ID>
<CNE>236724591</CNE>
<DateofBirth>1998-06-07</DateofBirth>
<FirstName>Dillon</FirstName>
<LastName>Skinner</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>04 59 17 82 66</Phone>
<Email>semper.Nam@Donecdignissimmagna.co.uk</Email>
</Student>
<Student>
<ID>25</ID>
<CNE>241611430</CNE>
<DateofBirth>1998-10-02</DateofBirth>
<FirstName>Lowe</FirstName>
<LastName>Burke</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>08 51 37 45 07</Phone>
<Email>mollis@iderat.net</Email>
</Student>
<Student>
<ID>26</ID>
<CNE>275827428</CNE>
<DateofBirth>1998-07-02</DateofBirth>
<FirstName>Burch</FirstName>
<LastName>Mcintosh</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>03 17 01 17 95</Phone>
<Email>Maecenas.mi.felis@variusultrices.edu</Email>
</Student>
<Student>
<ID>27</ID>
<CNE>153938534</CNE>
<DateofBirth>1998-10-18</DateofBirth>
<FirstName>Fuentes</FirstName>
<LastName>Gallagher</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>07 70 95 83 70</Phone>
<Email>Quisque.imperdiet@euismodmauriseu.org</Email>
</Student>
<Student>
<ID>28</ID>
<CNE>180686372</CNE>
<DateofBirth>1998-02-26</DateofBirth>
<FirstName>Monroe</FirstName>
<LastName>Hanson</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>08 82 82 68 40</Phone>
<Email>tortor.Integer@bibendum.co.uk</Email>
</Student>
<Student>
<ID>29</ID>
<CNE>191821000</CNE>
<DateofBirth>1998-03-04</DateofBirth>
<FirstName>Frye</FirstName>
<LastName>Mcgee</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>04 27 92 10 34</Phone>
<Email>ut.aliquam.iaculis@odio.org</Email>
</Student>
<Student>
<ID>30</ID>
<CNE>259847563</CNE>
<DateofBirth>1998-04-26</DateofBirth>
<FirstName>Warren</FirstName>
<LastName>Flynn</LastName>
<ClasseName>GSEA2</ClasseName>
<Phone>05 06 82 27 60</Phone>
<Email>sodales.purus@Phasellusdapibus.net</Email>
</Student>
</Students>

=== Mouadouakil/Students-Marks-System-Xml-Java/STUDENTS/Students_GIND3.xml
<?xml version="1.0" encoding="UTF-8"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Students.xsd">
<Student>
<ID>1</ID>
<CNE>385750298</CNE>
<DateofBirth>1997-08-08</DateofBirth>
<FirstName>Mitchell</FirstName>
<LastName>Stephens</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>09 77 78 32 85</Phone>
<Email>ornare.lectus.justo@imperdietnecleo.co.uk</Email>
</Student>
<Student>
<ID>2</ID>
<CNE>299174705</CNE>
<DateofBirth>1997-12-21</DateofBirth>
<FirstName>Conner</FirstName>
<LastName>Winters</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>02 53 42 53 96</Phone>
<Email>Vivamus.euismod.urna@aliquamenimnec.com</Email>
</Student>
<Student>
<ID>3</ID>
<CNE>307594514</CNE>
<DateofBirth>1997-04-18</DateofBirth>
<FirstName>Richmond</FirstName>
<LastName>Elliott</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>07 29 95 96 34</Phone>
<Email>Fusce@nec.com</Email>
</Student>
<Student>
<ID>4</ID>
<CNE>325673426</CNE>
<DateofBirth>1997-06-07</DateofBirth>
<FirstName>Abbott</FirstName>
<LastName>Kramer</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>05 30 75 95 76</Phone>
<Email>ac@ante.org</Email>
</Student>
<Student>
<ID>5</ID>
<CNE>298360929</CNE>
<DateofBirth>1997-09-19</DateofBirth>
<FirstName>Mendoza</FirstName>
<LastName>England</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>07 20 71 47 73</Phone>
<Email>amet.lorem.semper@volutpatnunc.com</Email>
</Student>
<Student>
<ID>6</ID>
<CNE>219695411</CNE>
<DateofBirth>1997-06-18</DateofBirth>
<FirstName>Slater</FirstName>
<LastName>Riddle</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>04 07 86 85 30</Phone>
<Email>Curabitur.vel@cubiliaCurae.ca</Email>
</Student>
<Student>
<ID>7</ID>
<CNE>187916625</CNE>
<DateofBirth>1997-01-27</DateofBirth>
<FirstName>Dominguez</FirstName>
<LastName>Oneill</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>06 29 68 73 45</Phone>
<Email>aliquet.libero.Integer@augue.org</Email>
</Student>
<Student>
<ID>8</ID>
<CNE>212600267</CNE>
<DateofBirth>1997-06-18</DateofBirth>
<FirstName>Osborne</FirstName>
<LastName>Foster</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>05 47 97 38 04</Phone>
<Email>vel.lectus.Cum@ipsumnuncid.com</Email>
</Student>
<Student>
<ID>9</ID>
<CNE>219850612</CNE>
<DateofBirth>1997-02-15</DateofBirth>
<FirstName>Benton</FirstName>
<LastName>Cruz</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>09 82 72 54 51</Phone>
<Email>Donec@vitaepurusgravida.ca</Email>
</Student>
<Student>
<ID>10</ID>
<CNE>336861001</CNE>
<DateofBirth>1997-10-31</DateofBirth>
<FirstName>Mcgowan</FirstName>
<LastName>Mckenzie</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>03 78 98 14 50</Phone>
<Email>vitae@gravida.org</Email>
</Student>
<Student>
<ID>11</ID>
<CNE>196518704</CNE>
<DateofBirth>1997-01-05</DateofBirth>
<FirstName>Robles</FirstName>
<LastName>Galloway</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>09 13 81 64 30</Phone>
<Email>eget@Donec.co.uk</Email>
</Student>
<Student>
<ID>12</ID>
<CNE>199431951</CNE>
<DateofBirth>1997-04-05</DateofBirth>
<FirstName>Miles</FirstName>
<LastName>Fuentes</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>03 91 92 24 16</Phone>
<Email>ipsum.primis@risus.ca</Email>
</Student>
<Student>
<ID>13</ID>
<CNE>220600492</CNE>
<DateofBirth>1997-03-02</DateofBirth>
<FirstName>Wynn</FirstName>
<LastName>Singleton</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>07 80 68 82 56</Phone>
<Email>Nunc.mauris@Maurismagna.co.uk</Email>
</Student>
<Student>
<ID>14</ID>
<CNE>286074367</CNE>
<DateofBirth>1997-05-17</DateofBirth>
<FirstName>Hanson</FirstName>
<LastName>Joyce</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>02 95 81 30 72</Phone>
<Email>ac.urna@interdumligula.co.uk</Email>
</Student>
<Student>
<ID>15</ID>
<CNE>209824808</CNE>
<DateofBirth>1997-12-05</DateofBirth>
<FirstName>Gentry</FirstName>
<LastName>Mcdaniel</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>09 78 65 34 94</Phone>
<Email>diam.luctus.lobortis@nuncestmollis.edu</Email>
</Student>
<Student>
<ID>16</ID>
<CNE>191708276</CNE>
<DateofBirth>1997-05-12</DateofBirth>
<FirstName>Maynard</FirstName>
<LastName>Hatfield</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>01 64 84 59 69</Phone>
<Email>ante@vestibulum.net</Email>
</Student>
<Student>
<ID>17</ID>
<CNE>222072253</CNE>
<DateofBirth>1997-08-09</DateofBirth>
<FirstName>Dudley</FirstName>
<LastName>Mccarthy</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>05 49 97 79 40</Phone>
<Email>enim.Mauris.quis@aliquamenimnec.net</Email>
</Student>
<Student>
<ID>18</ID>
<CNE>354668848</CNE>
<DateofBirth>1997-03-31</DateofBirth>
<FirstName>Hudson</FirstName>
<LastName>Maxwell</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>03 32 02 86 93</Phone>
<Email>amet@interdum.edu</Email>
</Student>
<Student>
<ID>19</ID>
<CNE>331435444</CNE>
<DateofBirth>1997-07-20</DateofBirth>
<FirstName>Best</FirstName>
<LastName>Snyder</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>02 33 36 07 77</Phone>
<Email>est.Mauris.eu@ante.edu</Email>
</Student>
<Student>
<ID>20</ID>
<CNE>226074160</CNE>
<DateofBirth>1997-12-05</DateofBirth>
<FirstName>Wilder</FirstName>
<LastName>Rivers</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>03 95 91 27 86</Phone>
<Email>ac.risus.Morbi@ridiculusmusAenean.edu</Email>
</Student>
<Student>
<ID>21</ID>
<CNE>379893501</CNE>
<DateofBirth>1997-03-31</DateofBirth>
<FirstName>Henderson</FirstName>
<LastName>Sharpe</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>05 83 42 33 89</Phone>
<Email>luctus@ligula.co.uk</Email>
</Student>
<Student>
<ID>22</ID>
<CNE>237749193</CNE>
<DateofBirth>1997-07-20</DateofBirth>
<FirstName>Dale</FirstName>
<LastName>Durham</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>08 15 25 88 52</Phone>
<Email>elit.pretium.et@Nam.net</Email>
</Student>
<Student>
<ID>23</ID>
<CNE>357515866</CNE>
<DateofBirth>1997-04-30</DateofBirth>
<FirstName>Doyle</FirstName>
<LastName>Martin</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>09 39 67 45 80</Phone>
<Email>odio.Phasellus@arcu.edu</Email>
</Student>
<Student>
<ID>24</ID>
<CNE>390220651</CNE>
<DateofBirth>1997-07-06</DateofBirth>
<FirstName>Ware</FirstName>
<LastName>Maldonado</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>08 15 51 03 63</Phone>
<Email>interdum.Nunc@Etiamgravidamolestie.ca</Email>
</Student>
<Student>
<ID>25</ID>
<CNE>368862556</CNE>
<DateofBirth>1998-08-08</DateofBirth>
<FirstName>Shields</FirstName>
<LastName>Richards</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>02 10 30 87 45</Phone>
<Email>vel@interdumCurabiturdictum.com</Email>
</Student>
<Student>
<ID>26</ID>
<CNE>320440900</CNE>
<DateofBirth>1998-12-21</DateofBirth>
<FirstName>Craig</FirstName>
<LastName>Fields</LastName>
<ClasseName>GIND3</ClasseName>
<Phone>09 24 76 22 71</Phone>
<Email>sed@Phasellusdolor.org</Email>
</Student>
</Students>

=== Mouadouakil/Students-Marks-System-Xml-Java/STUDENTS/Students_G3EI1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Students.xsd">
<Student>
<ID>1</ID>
<CNE>228759693</CNE>
<DateofBirth>1999-10-11</DateofBirth>
<FirstName>Aguirre</FirstName>
<LastName>Clark</LastName>
<ClasseName>G3EI1</ClasseName>
<Phone>08 06 98 97 19</Phone>
<Email>Donec.est.mauris@dictumplacerataugue.com</Email>
</Student>
<Student>
<ID>2</ID>
<CNE>217009019</CNE>
<DateofBirth>1999-08-01</DateofBirth>
<FirstName>Odom</FirstName>
<LastName>Miles</LastName>
<ClasseName>G3EI1</ClasseName>
<Phone>09 80 09 24 50</Phone>
<Email>Curabitur.dictum.Phasellus@ridiculusmusAenean.com</Email>
</Student>
<Student>
<ID>3</ID>
<CNE>253172430</CNE>
<DateofBirth>1999-06-09</DateofBirth>
<FirstName>Rich</FirstName>
<LastName>Fowler</LastName>
<ClasseName>G3EI1</ClasseName>
<Phone>04 03 86 37 20</Phone>
<Email>semper@ipsumPhasellus.edu</Email>
</Student>
<Student>
<ID>4</ID>
<CNE>270185581</CNE>
<DateofBirth>1999-04-06</DateofBirth>
<FirstName>Obrien</FirstName>
<LastName>Ratliff</LastName>
<ClasseName>G3EI1</ClasseName>
<Phone>04 04 81 99 78</Phone>
<Email>litora.torquent.per@nuncnullavulputate.org</Email>
</Student>
<Student>
<ID>5</ID>
<CNE>285509684</CNE>
<DateofBirth>1999-06-28</DateofBirth>
<FirstName>Bridges</FirstName>
<LastName>Estrada</LastName>
<ClasseName>G3EI1</ClasseName>
<Phone>03 04 58 05 55</Phone>
<Email>Nunc@liberoProin.net</Email>
</Student>
<Student>
<ID>6</ID>
<CNE>207598720</CNE>
<DateofBirth>1999-09-28</DateofBirth>
<FirstName>White</FirstName>
<LastName>Rocha</LastName>
<ClasseName>G3EI1</ClasseName>
<Phone>09 27 20 40 68</Phone>
<Email>lectus@magnisdis.net</Email>
</Student>
<Student>
<ID>7</ID>
<CNE>251351354</CNE>
<DateofBirth>1999-03-12</DateofBirth>
<FirstName>Hardin</FirstName>
<LastName>Howe</LastName>
<ClasseName>G3EI1</ClasseName>
<Phone>05 11 07 82 45</Phone>
<Email>velit.Cras.lorem@Integer.co.uk</Email>
</Student>
<Student>
<ID>8</ID>
<CNE>298589351</CNE>
<DateofBirth>1999-05-15</DateofBirth>
<FirstName>Hoover</FirstName>
<LastName>Chapman</LastName>
<ClasseName>G3EI1</ClasseName>
<Phone>04 17 74 61 29</Phone>
<Email>consectetuer.rhoncus.Nullam@faucibus.org</Email>
</Student>
<Student>
<ID>9</ID>
<CNE>182607361</CNE>
<DateofBirth>1999-02-16</DateofBirth>
<FirstName>Gilmore</FirstName>
<LastName>Jackson</LastName>
<ClasseName>G3EI1</ClasseName>
<Phone>04 94 88 62 41</Phone>
<Email>imperdiet@nullaInteger.co.uk</Email>
</Student>
<Student>
<ID>10</ID>
<CNE>259495670</CNE>
<DateofBirth>1999-03-19</DateofBirth>
<FirstName>Hunter</FirstName>
<LastName>Bradford</LastName>
<ClasseName>G3EI1</ClasseName>
<Phone>07 18 73 74 58</Phone>
<Email>ultrices.Vivamus@ut.org</Email>
</Student>
<Student>
<ID>11</ID>
<CNE>210287353</CNE>
<DateofBirth>1999-09-13</DateofBirth>
<FirstName>Miller</FirstName>
<LastName>Gallagher</LastName>
<ClasseName>G3EI1</ClasseName>
<Phone>05 10 30 16 59</Phone>
<Email>tempus.lorem@consequat.net</Email>
</Student>
<Student>
<ID>12</ID>
<CNE>289556745</CNE>
<DateofBirth>1999-08-08</DateofBirth>
<FirstName>Blair</FirstName>
<LastName>Preston</LastName>
<ClasseName>G3EI1</ClasseName>
<Phone>04 14 50 74 60</Phone>
<Email>cursus@risusNullaeget.com</Email>
</Student>
<Student>
<ID>13</ID>
<CNE>274410266</CNE>
<DateofBirth>1999-04-23</DateofBirth>
<FirstName>Mccall</FirstName>
<LastName>Guerra</LastName>
<ClasseName>G3EI1</ClasseName>
<Phone>03 06 47 63 47</Phone>
<Email>ultrices.mauris@tincidunt.ca</Email>
</Student>
<Student>
<ID>14</ID>
<CNE>215046071</CNE>
<DateofBirth>1999-09-09</DateofBirth>
<FirstName>Hancock</FirstName>
<LastName>Dotson</LastName>
<ClasseName>G3EI1</ClasseName>
<Phone>02 43 07 94 37</Phone>
<Email>ullamcorper.velit.in@metusurnaconvallis.com</Email>
</Student>
<Student>
<ID>15</ID>
<CNE>192729204</CNE>
<DateofBirth>1999-03-26</DateofBirth>
<FirstName>Hebert</FirstName>
<LastName>Estrada</LastName>
<ClasseName>G3EI1</ClasseName>
<Phone>01 75 73 91 04</Phone>
<Email>felis.Donec@pretium.org</Email>
</Student>
<Student>
<ID>16</ID>
<CNE>257887552</CNE>
<DateofBirth>1999-02-04</DateofBirth>
<FirstName>Cooley</FirstName>
<LastName>Carpenter</LastName>
<ClasseName>G3EI1</ClasseName>
<Phone>01 64 47 34 98</Phone>
<Email>neque.vitae@tristiqueaceleifend.org</Email>
</Student>
<Student>
<ID>17</ID>
<CNE>187696011</CNE>
<DateofBirth>1999-07-17</DateofBirth>
<FirstName>Barrett</FirstName>
<LastName>Mcintosh</LastName>
<ClasseName>G3EI1</ClasseName>
<Phone>04 13 91 30 02</Phone>
<Email>Fusce.aliquam.enim@augueidante.net</Email>
</Student>
<Student>
<ID>18</ID>
<CNE>209040425</CNE>
<DateofBirth>1999-05-27</DateofBirth>
<FirstName>Black</FirstName>
<LastName>Dickson</LastName>
<ClasseName>G3EI1</ClasseName>
<Phone>02 26 16 44 66</Phone>
<Email>tristique.senectus.et@neque.org</Email>
</Student>
<Student>
<ID>19</ID>
<CNE>250747341</CNE>
<DateofBirth>1999-04-22</DateofBirth>
<FirstName>Briggs</FirstName>
<LastName>Dudley</LastName>
<ClasseName>G3EI1</ClasseName>
<Phone>02 35 90 24 46</Phone>
<Email>lectus.a@arcu.co.uk</Email>
</Student>
<Student>
<ID>20</ID>
<CNE>237382665</CNE>
<DateofBirth>1999-04-14</DateofBirth>
<FirstName>Stafford</FirstName>
<LastName>Harmon</LastName>
<ClasseName>G3EI1</ClasseName>
<Phone>03 65 11 90 37</Phone>
<Email>fringilla.cursus.purus@porttitorscelerisque.org</Email>
</Student>
<Student>
<ID>21</ID>
<CNE>299493655</CNE>
<DateofBirth>1999-08-14</DateofBirth>
<FirstName>Ward</FirstName>
<LastName>England</LastName>
<ClasseName>G3EI1</ClasseName>
<Phone>03 00 44 64 58</Phone>
<Email>ultricies.dignissim@fringillaornare.com</Email>
</Student>
<Student>
<ID>22</ID>
<CNE>286808919</CNE>
<DateofBirth>1999-09-09</DateofBirth>
<FirstName>Ewing</FirstName>
<LastName>Simon</LastName>
<ClasseName>G3EI1</ClasseName>
<Phone>07 13 80 48 54</Phone>
<Email>elit.a.feugiat@sitamet.ca</Email>
</Student>
</Students>
