=== Mouadouakil/Students-Marks-System-Xml-Java/STUDENTS/Students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="Students">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Student" minOccurs="1" maxOccurs="unbounded">   
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ID" type="xs:integer"/>
                            <xs:element name="CNE" type="xs:string"/>
                            <xs:element name="DateofBirth" type="xs:date"/>
                            <xs:element name="FirstName" minOccurs="1" maxOccurs="unbounded" >
                              <xs:simpleType>
                                  <xs:restriction base="xs:string">
                                      <xs:pattern value="([a-zA-z])*"/>
                                  </xs:restriction>
                              </xs:simpleType>  
                            </xs:element>
                           
                            <xs:element name="LastName" minOccurs="1" maxOccurs="unbounded">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="([a-zA-z])*"/>
                                    </xs:restriction>
                                </xs:simpleType>  
                            </xs:element>
                            
                            <xs:element name="ClasseName" type="xs:string"/>
                            <xs:element name="Phone" type="xs:string"/>
                            <xs:element name="Email" type="xs:string"/>
                       </xs:sequence>
                        <xs:attribute name="id" type="xs:positiveInteger" use="optional"/>
                    </xs:complexType> 
                </xs:element>
            </xs:sequence>
 
        </xs:complexType>
    </xs:element>   
</xs:schema>

=== Mouadouakil/Students-Marks-System-Xml-Java/STUDENTS/Students_GIND1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Students.xsd">
<Student>
<ID>1</ID>
<CNE>251881103</CNE>
<DateofBirth>1999-11-23</DateofBirth>
<FirstName>Adams</FirstName>
<LastName>Gaines</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>01 38 81 89 01</Phone>
<Email>blandit@tristique.edu</Email>
</Student>
<Student>
<ID>2</ID>
<CNE>255568226</CNE>
<DateofBirth>1999-11-16</DateofBirth>
<FirstName>Golden</FirstName>
<LastName>Jennings</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>02 89 28 91 32</Phone>
<Email>quis.tristique@metuseu.com</Email>
</Student>
<Student>
<ID>3</ID>
<CNE>341062185</CNE>
<DateofBirth>1999-10-01</DateofBirth>
<FirstName>Avery</FirstName>
<LastName>Small</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>04 97 38 50 09</Phone>
<Email>non@MorbimetusVivamus.ca</Email>
</Student>
<Student>
<ID>4</ID>
<CNE>202494596</CNE>
<DateofBirth>1999-03-08</DateofBirth>
<FirstName>Carr</FirstName>
<LastName>Richard</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>05 20 05 81 58</Phone>
<Email>Mauris@acarcuNunc.com</Email>
</Student>
<Student>
<ID>5</ID>
<CNE>210910547</CNE>
<DateofBirth>1999-08-04</DateofBirth>
<FirstName>Erickson</FirstName>
<LastName>Wolf</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>02 27 19 03 01</Phone>
<Email>lacinia@a.org</Email>
</Student>
<Student>
<ID>6</ID>
<CNE>233205753</CNE>
<DateofBirth>1999-07-22</DateofBirth>
<FirstName>Shepherd</FirstName>
<LastName>Keller</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>02 18 22 36 44</Phone>
<Email>mi.lacinia.mattis@rutrumFuscedolor.edu</Email>
</Student>
<Student>
<ID>7</ID>
<CNE>354928604</CNE>
<DateofBirth>1999-05-14</DateofBirth>
<FirstName>Boyd</FirstName>
<LastName>Acosta</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>05 65 37 09 27</Phone>
<Email>a.felis.ullamcorper@eratvolutpat.com</Email>
</Student>
<Student>
<ID>8</ID>
<CNE>181489388</CNE>
<DateofBirth>1999-06-01</DateofBirth>
<FirstName>Colon</FirstName>
<LastName>Ingram</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>08 24 84 67 06</Phone>
<Email>justo@nuncsed.com</Email>
</Student>
<Student>
<ID>9</ID>
<CNE>270051286</CNE>
<DateofBirth>1999-07-18</DateofBirth>
<FirstName>Patel</FirstName>
<LastName>Middleton</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>03 74 62 15 54</Phone>
<Email>sem.elit.pharetra@necmetusfacilisis.net</Email>
</Student>
<Student>
<ID>10</ID>
<CNE>378320299</CNE>
<DateofBirth>1999-04-19</DateofBirth>
<FirstName>Joseph</FirstName>
<LastName>Ferguson</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>09 29 47 77 85</Phone>
<Email>Proin.sed@egestasurna.net</Email>
</Student>
<Student>
<ID>11</ID>
<CNE>216131447</CNE>
<DateofBirth>1999-08-08</DateofBirth>
<FirstName>Mejia</FirstName>
<LastName>Lawrence</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>08 63 70 10 06</Phone>
<Email>sit.amet@vulputate.edu</Email>
</Student>
<Student>
<ID>12</ID>
<CNE>383318553</CNE>
<DateofBirth>1999-03-28</DateofBirth>
<FirstName>Sawyer</FirstName>
<LastName>Tyson</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>04 36 21 44 94</Phone>
<Email>metus@Pellentesquehabitantmorbi.co.uk</Email>
</Student>
<Student>
<ID>13</ID>
<CNE>228211841</CNE>
<DateofBirth>1999-05-18</DateofBirth>
<FirstName>Vance</FirstName>
<LastName>Sweet</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>01 47 54 62 16</Phone>
<Email>est@estMauriseu.ca</Email>
</Student>
<Student>
<ID>14</ID>
<CNE>369818034</CNE>
<DateofBirth>1999-05-09</DateofBirth>
<FirstName>Harrington</FirstName>
<LastName>Hicks</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>04 69 65 48 61</Phone>
<Email>purus.Maecenas.libero@Curabitursed.co.uk</Email>
</Student>
<Student>
<ID>15</ID>
<CNE>234559474</CNE>
<DateofBirth>1999-04-13</DateofBirth>
<FirstName>Fitzpatrick</FirstName>
<LastName>Cole</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>04 45 96 33 89</Phone>
<Email>Vivamus.euismod.urna@sapienimperdietornare.ca</Email>
</Student>
<Student>
<ID>16</ID>
<CNE>208587108</CNE>
<DateofBirth>1999-08-10</DateofBirth>
<FirstName>Sandoval</FirstName>
<LastName>Clarke</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>07 81 03 47 84</Phone>
<Email>eu.neque.pellentesque@eu.org</Email>
</Student>
<Student>
<ID>17</ID>
<CNE>250482377</CNE>
<DateofBirth>1999-02-14</DateofBirth>
<FirstName>Norman</FirstName>
<LastName>Christensen</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>07 01 12 21 46</Phone>
<Email>nisi.magna.sed@odio.org</Email>
</Student>
<Student>
<ID>18</ID>
<CNE>245580817</CNE>
<DateofBirth>1999-11-09</DateofBirth>
<FirstName>Owen</FirstName>
<LastName>West</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>07 01 76 32 24</Phone>
<Email>fringilla.cursus@lacus.ca</Email>
</Student>
<Student>
<ID>19</ID>
<CNE>240340903</CNE>
<DateofBirth>1999-10-28</DateofBirth>
<FirstName>Wilder</FirstName>
<LastName>Shaw</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>01 68 99 70 13</Phone>
<Email>Mauris@semperauctorMauris.co.uk</Email>
</Student>
<Student>
<ID>20</ID>
<CNE>306944921</CNE>
<DateofBirth>1999-03-25</DateofBirth>
<FirstName>Roy</FirstName>
<LastName>Moses</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>09 70 08 10 99</Phone>
<Email>Sed@nonduinec.edu</Email>
</Student>
<Student>
<ID>21</ID>
<CNE>170142748</CNE>
<DateofBirth>1999-05-24</DateofBirth>
<FirstName>Pierce</FirstName>
<LastName>Moran</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>01 19 37 71 18</Phone>
<Email>habitant.morbi.tristique@Duis.com</Email>
</Student>
<Student>
<ID>22</ID>
<CNE>386648008</CNE>
<DateofBirth>1999-02-06</DateofBirth>
<FirstName>Rosario</FirstName>
<LastName>Casey</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>05 41 67 32 03</Phone>
<Email>in.faucibus.orci@Sed.edu</Email>
</Student>
<Student>
<ID>23</ID>
<CNE>280975576</CNE>
<DateofBirth>1999-09-17</DateofBirth>
<FirstName>Holder</FirstName>
<LastName>Horn</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>09 44 24 60 80</Phone>
<Email>dictum.eu.eleifend@vitae.edu</Email>
</Student>
<Student>
<ID>24</ID>
<CNE>291083805</CNE>
<DateofBirth>1999-11-22</DateofBirth>
<FirstName>Witt</FirstName>
<LastName>Ryan</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>07 03 65 36 24</Phone>
<Email>purus@auctornuncnulla.org</Email>
</Student>
<Student>
<ID>25</ID>
<CNE>396620290</CNE>
<DateofBirth>1999-09-23</DateofBirth>
<FirstName>Hicks</FirstName>
<LastName>Lara</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>07 03 85 93 87</Phone>
<Email>interdum.Curabitur.dictum@utipsum.co.uk</Email>
</Student>
<Student>
<ID>26</ID>
<CNE>254355908</CNE>
<DateofBirth>1999-03-24</DateofBirth>
<FirstName>Vargas</FirstName>
<LastName>Mcfadden</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>08 93 76 80 09</Phone>
<Email>orci.Ut@lobortisClass.ca</Email>
</Student>
<Student>
<ID>27</ID>
<CNE>185394551</CNE>
<DateofBirth>1999-04-05</DateofBirth>
<FirstName>Atkinson</FirstName>
<LastName>Patton</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>08 22 64 88 89</Phone>
<Email>In@egestasFuscealiquet.co.uk</Email>
</Student>
<Student>
<ID>28</ID>
<CNE>259349478</CNE>
<DateofBirth>1999-02-07</DateofBirth>
<FirstName>Paul</FirstName>
<LastName>Whitehead</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>02 83 85 29 91</Phone>
<Email>ac.tellus.Suspendisse@tristiquepellentesque.edu</Email>
</Student>
<Student>
<ID>29</ID>
<CNE>201706012</CNE>
<DateofBirth>1999-06-26</DateofBirth>
<FirstName>Wilkins</FirstName>
<LastName>Serrano</LastName>
<ClasseName>GIND1</ClasseName>
<Phone>02 26 64 96 49</Phone>
<Email>ac.mattis.ornare@congue.com</Email>
</Student>
</Students>

=== Mouadouakil/Students-Marks-System-Xml-Java/STUDENTS/Students_GINF3.xml
<?xml version="1.0" encoding="UTF-8"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Students.xsd">
<Student>
<ID>1</ID>
<CNE>187349082</CNE>
<DateofBirth>1997-10-09</DateofBirth>
<FirstName>Wade</FirstName>
<LastName>Sellers</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>09 16 83 52 98</Phone>
<Email>lectus@arcuCurabitur.net</Email>
</Student>
<Student>
<ID>2</ID>
<CNE>195003603</CNE>
<DateofBirth>1997-07-11</DateofBirth>
<FirstName>Crosby</FirstName>
<LastName>Rosario</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>09 38 70 01 97</Phone>
<Email>Donec@a.co.uk</Email>
</Student>
<Student>
<ID>3</ID>
<CNE>181385492</CNE>
<DateofBirth>1997-07-28</DateofBirth>
<FirstName>Odom</FirstName>
<LastName>Jenkins</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>09 08 78 58 99</Phone>
<Email>vulputate@adipiscingfringilla.co.uk</Email>
</Student>
<Student>
<ID>4</ID>
<CNE>191593229</CNE>
<DateofBirth>1997-09-22</DateofBirth>
<FirstName>Walters</FirstName>
<LastName>Lucas</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>05 90 92 11 36</Phone>
<Email>consectetuer.euismod@ullamcorper.edu</Email>
</Student>
<Student>
<ID>5</ID>
<CNE>184388256</CNE>
<DateofBirth>1997-02-11</DateofBirth>
<FirstName>Cruz</FirstName>
<LastName>Lambert</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>04 14 96 95 40</Phone>
<Email>non.feugiat.nec@atauctorullamcorper.net</Email>
</Student>
<Student>
<ID>6</ID>
<CNE>191834513</CNE>
<DateofBirth>1997-02-28</DateofBirth>
<FirstName>Oliver</FirstName>
<LastName>Yates</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>09 39 78 46 09</Phone>
<Email>sit.amet@asollicitudinorci.ca</Email>
</Student>
<Student>
<ID>7</ID>
<CNE>173799304</CNE>
<DateofBirth>1997-06-15</DateofBirth>
<FirstName>Pate</FirstName>
<LastName>Kline</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>02 41 57 67 44</Phone>
<Email>in@Morbiaccumsan.net</Email>
</Student>
<Student>
<ID>8</ID>
<CNE>178729539</CNE>
<DateofBirth>1997-09-14</DateofBirth>
<FirstName>Mcpherson</FirstName>
<LastName>Carroll</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>02 32 58 90 14</Phone>
<Email>pellentesque.eget.dictum@convallisest.net</Email>
</Student>
<Student>
<ID>9</ID>
<CNE>187793784</CNE>
<DateofBirth>1997-10-06</DateofBirth>
<FirstName>Conley</FirstName>
<LastName>Cobb</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>06 22 54 89 58</Phone>
<Email>Aliquam@posuere.org</Email>
</Student>
<Student>
<ID>10</ID>
<CNE>198012327</CNE>
<DateofBirth>1997-03-31</DateofBirth>
<FirstName>Noel</FirstName>
<LastName>Fuller</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>05 35 78 39 14</Phone>
<Email>non@magnaCrasconvallis.com</Email>
</Student>
<Student>
<ID>11</ID>
<CNE>174873310</CNE>
<DateofBirth>1997-06-29</DateofBirth>
<FirstName>Delgado</FirstName>
<LastName>Hudson</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>03 45 88 33 87</Phone>
<Email>malesuada.vel.convallis@ultricesposuerecubilia.com</Email>
</Student>
<Student>
<ID>12</ID>
<CNE>186455166</CNE>
<DateofBirth>1997-01-12</DateofBirth>
<FirstName>Bentley</FirstName>
<LastName>Ross</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>08 17 18 21 30</Phone>
<Email>est@Nuncsed.ca</Email>
</Student>
<Student>
<ID>13</ID>
<CNE>193026033</CNE>
<DateofBirth>1997-02-03</DateofBirth>
<FirstName>Larson</FirstName>
<LastName>Potts</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>06 41 19 34 32</Phone>
<Email>Cras.interdum.Nunc@enimNunc.org</Email>
</Student>
<Student>
<ID>14</ID>
<CNE>189876898</CNE>
<DateofBirth>1997-02-18</DateofBirth>
<FirstName>Oconnor</FirstName>
<LastName>Hopkins</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>08 34 20 86 52</Phone>
<Email>erat.neque@laoreetlectus.org</Email>
</Student>
<Student>
<ID>15</ID>
<CNE>184092273</CNE>
<DateofBirth>1997-01-21</DateofBirth>
<FirstName>Tyler</FirstName>
<LastName>Savage</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>02 98 23 46 62</Phone>
<Email>massa.Suspendisse.eleifend@nonenim.com</Email>
</Student>
<Student>
<ID>16</ID>
<CNE>163263347</CNE>
<DateofBirth>1997-09-03</DateofBirth>
<FirstName>Lynch</FirstName>
<LastName>Kidd</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>03 64 83 64 23</Phone>
<Email>nec.tellus@lectusquismassa.edu</Email>
</Student>
<Student>
<ID>17</ID>
<CNE>160178804</CNE>
<DateofBirth>1997-06-20</DateofBirth>
<FirstName>Dickerson</FirstName>
<LastName>Boyer</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>04 62 32 29 10</Phone>
<Email>Suspendisse.commodo@estac.net</Email>
</Student>
<Student>
<ID>18</ID>
<CNE>161373907</CNE>
<DateofBirth>1997-07-05</DateofBirth>
<FirstName>Sparks</FirstName>
<LastName>Merrill</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>07 11 01 98 90</Phone>
<Email>nonummy.Fusce@Donecat.org</Email>
</Student>
<Student>
<ID>19</ID>
<CNE>173921748</CNE>
<DateofBirth>1997-10-31</DateofBirth>
<FirstName>Tucker</FirstName>
<LastName>Elliott</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>08 90 39 99 25</Phone>
<Email>vel.turpis.Aliquam@acmi.com</Email>
</Student>
<Student>
<ID>20</ID>
<CNE>196061530</CNE>
<DateofBirth>1997-09-11</DateofBirth>
<FirstName>Mcconnell</FirstName>
<LastName>Dyer</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>09 06 64 09 53</Phone>
<Email>turpis@risusquis.co.uk</Email>
</Student>
<Student>
<ID>21</ID>
<CNE>193710775</CNE>
<DateofBirth>1997-04-21</DateofBirth>
<FirstName>Calderon</FirstName>
<LastName>Gallegos</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>01 75 18 36 60</Phone>
<Email>elit@ipsum.ca</Email>
</Student>
<Student>
<ID>22</ID>
<CNE>161551408</CNE>
<DateofBirth>1997-01-07</DateofBirth>
<FirstName>Finley</FirstName>
<LastName>Bray</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>05 49 65 26 71</Phone>
<Email>et.ultrices.posuere@nonmagna.org</Email>
</Student>
<Student>
<ID>23</ID>
<CNE>191342069</CNE>
<DateofBirth>1997-09-21</DateofBirth>
<FirstName>Crane</FirstName>
<LastName>Robbins</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>04 28 72 83 15</Phone>
<Email>iaculis.quis.pede@Sedetlibero.net</Email>
</Student>
<Student>
<ID>24</ID>
<CNE>180806967</CNE>
<DateofBirth>1997-07-17</DateofBirth>
<FirstName>Farmer</FirstName>
<LastName>Lucas</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>06 74 00 95 37</Phone>
<Email>semper.pretium@odiosagittissemper.org</Email>
</Student>
<Student>
<ID>25</ID>
<CNE>182146215</CNE>
<DateofBirth>1997-03-19</DateofBirth>
<FirstName>Holcomb</FirstName>
<LastName>Navarro</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>07 68 27 90 57</Phone>
<Email>Cras.lorem@senectuset.org</Email>
</Student>
<Student>
<ID>26</ID>
<CNE>176851333</CNE>
<DateofBirth>1997-07-30</DateofBirth>
<FirstName>Whitney</FirstName>
<LastName>Hooper</LastName>
<ClasseName>GINF3</ClasseName>
<Phone>01 22 04 25 69</Phone>
<Email>Phasellus@laciniaatiaculis.com</Email>
</Student>
</Students>

=== Mouadouakil/Students-Marks-System-Xml-Java/STUDENTS/Students_GSEA3.xml
<?xml version="1.0" encoding="UTF-8"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Students.xsd">
<Student>
<ID>1</ID>
<CNE>307594514</CNE>
<DateofBirth>1997-10-09</DateofBirth>
<FirstName>Fitzgerald</FirstName>
<LastName>Cotton</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>05 70 31 03 97</Phone>
<Email>non.sapien.molestie@disparturientmontes.org</Email>
</Student>
<Student>
<ID>2</ID>
<CNE>325673426</CNE>
<DateofBirth>1997-07-11</DateofBirth>
<FirstName>Pickett</FirstName>
<LastName>Norris</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>04 28 74 58 14</Phone>
<Email>dui.Cum@id.co.uk</Email>
</Student>
<Student>
<ID>3</ID>
<CNE>298360929</CNE>
<DateofBirth>1997-07-28</DateofBirth>
<FirstName>Hale</FirstName>
<LastName>Wheeler</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>06 41 94 58 22</Phone>
<Email>lacus.varius@nonleo.co.uk</Email>
</Student>
<Student>
<ID>4</ID>
<CNE>219695411</CNE>
<DateofBirth>1997-09-22</DateofBirth>
<FirstName>Benjamin</FirstName>
<LastName>Michael</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>07 62 33 28 32</Phone>
<Email>Curae.Phasellus@imperdiet.net</Email>
</Student>
<Student>
<ID>5</ID>
<CNE>187916625</CNE>
<DateofBirth>1997-02-11</DateofBirth>
<FirstName>Bowen</FirstName>
<LastName>Stanton</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>06 21 55 91 71</Phone>
<Email>eu@ametornare.ca</Email>
</Student>
<Student>
<ID>6</ID>
<CNE>212600267</CNE>
<DateofBirth>1997-02-28</DateofBirth>
<FirstName>Oconnor</FirstName>
<LastName>Richmond</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>04 71 68 28 30</Phone>
<Email>tincidunt.vehicula.risus@diam.edu</Email>
</Student>
<Student>
<ID>7</ID>
<CNE>219850612</CNE>
<DateofBirth>1997-06-15</DateofBirth>
<FirstName>Cooke</FirstName>
<LastName>Rivers</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>02 13 48 87 98</Phone>
<Email>lorem.semper@Donec.edu</Email>
</Student>
<Student>
<ID>8</ID>
<CNE>336861001</CNE>
<DateofBirth>1997-09-14</DateofBirth>
<FirstName>Beach</FirstName>
<LastName>Vaughan</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>09 13 47 76 47</Phone>
<Email>convallis@ornare.co.uk</Email>
</Student>
<Student>
<ID>9</ID>
<CNE>196518704</CNE>
<DateofBirth>1997-10-06</DateofBirth>
<FirstName>Gallagher</FirstName>
<LastName>Romero</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>02 51 87 59 40</Phone>
<Email>rutrum.lorem@aliquameu.edu</Email>
</Student>
<Student>
<ID>10</ID>
<CNE>199431951</CNE>
<DateofBirth>1997-03-31</DateofBirth>
<FirstName>Spencer</FirstName>
<LastName>Woods</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>03 88 05 01 65</Phone>
<Email>amet.lorem@SuspendisseduiFusce.co.uk</Email>
</Student>
<Student>
<ID>11</ID>
<CNE>220600492</CNE>
<DateofBirth>1997-06-29</DateofBirth>
<FirstName>Hampton</FirstName>
<LastName>Hester</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>01 70 49 79 06</Phone>
<Email>neque@aarcu.org</Email>
</Student>
<Student>
<ID>12</ID>
<CNE>286074367</CNE>
<DateofBirth>1997-01-12</DateofBirth>
<FirstName>Gates</FirstName>
<LastName>Figueroa</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>06 74 74 54 27</Phone>
<Email>Curabitur@malesuadafames.ca</Email>
</Student>
<Student>
<ID>13</ID>
<CNE>209824808</CNE>
<DateofBirth>1997-02-03</DateofBirth>
<FirstName>Fischer</FirstName>
<LastName>Dominguez</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>02 94 26 57 43</Phone>
<Email>parturient.montes.nascetur@Vivamussitamet.ca</Email>
</Student>
<Student>
<ID>14</ID>
<CNE>191708276</CNE>
<DateofBirth>1997-02-18</DateofBirth>
<FirstName>Puckett</FirstName>
<LastName>George</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>03 88 71 42 78</Phone>
<Email>augue@loremeget.edu</Email>
</Student>
<Student>
<ID>15</ID>
<CNE>222072253</CNE>
<DateofBirth>1997-01-21</DateofBirth>
<FirstName>Glover</FirstName>
<LastName>Mcknight</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>07 06 11 77 77</Phone>
<Email>tempus.mauris.erat@neceuismod.net</Email>
</Student>
<Student>
<ID>16</ID>
<CNE>16020307</CNE>
<DateofBirth>1997-09-03</DateofBirth>
<FirstName>Mays</FirstName>
<LastName>Wilder</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>02 08 80 60 30</Phone>
<Email>et.netus.et@Curabiturdictum.edu</Email>
</Student>
<Student>
<ID>17</ID>
<CNE>16871112</CNE>
<DateofBirth>1997-06-20</DateofBirth>
<FirstName>Rocha</FirstName>
<LastName>Wilkinson</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>06 74 29 24 48</Phone>
<Email>libero@Nullam.com</Email>
</Student>
<Student>
<ID>18</ID>
<CNE>16301010</CNE>
<DateofBirth>1997-07-05</DateofBirth>
<FirstName>Rich</FirstName>
<LastName>Smith</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>07 97 45 17 28</Phone>
<Email>malesuada.vel.convallis@risus.edu</Email>
</Student>
<Student>
<ID>19</ID>
<CNE>16530228</CNE>
<DateofBirth>1997-10-31</DateofBirth>
<FirstName>Mack</FirstName>
<LastName>Larson</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>07 36 51 51 40</Phone>
<Email>tempor@eratvolutpatNulla.edu</Email>
</Student>
<Student>
<ID>20</ID>
<CNE>16140326</CNE>
<DateofBirth>1997-09-11</DateofBirth>
<FirstName>Reid</FirstName>
<LastName>Morris</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>04 34 92 29 19</Phone>
<Email>et.netus.et@Vivamusnonlorem.ca</Email>
</Student>
<Student>
<ID>21</ID>
<CNE>16400928</CNE>
<DateofBirth>1997-04-21</DateofBirth>
<FirstName>Moses</FirstName>
<LastName>Lang</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>01 23 48 03 09</Phone>
<Email>Curabitur@etlacinia.co.uk</Email>
</Student>
<Student>
<ID>22</ID>
<CNE>16450723</CNE>
<DateofBirth>1997-01-07</DateofBirth>
<FirstName>Short</FirstName>
<LastName>Burgess</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>02 88 40 72 94</Phone>
<Email>vel@adlitoratorquent.edu</Email>
</Student>
<Student>
<ID>23</ID>
<CNE>16220519</CNE>
<DateofBirth>1997-09-21</DateofBirth>
<FirstName>Stone</FirstName>
<LastName>Tanner</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>06 57 97 50 94</Phone>
<Email>Quisque.nonummy@lectusNullam.org</Email>
</Student>
<Student>
<ID>24</ID>
<CNE>16831227</CNE>
<DateofBirth>1997-07-17</DateofBirth>
<FirstName>Sparks</FirstName>
<LastName>Fields</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>09 04 96 53 21</Phone>
<Email>sociis@euismodurnaNullam.org</Email>
</Student>
<Student>
<ID>25</ID>
<CNE>16020130</CNE>
<DateofBirth>1997-03-19</DateofBirth>
<FirstName>Solomon</FirstName>
<LastName>Madden</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>06 56 45 38 00</Phone>
<Email>quis@vestibulumneque.org</Email>
</Student>
<Student>
<ID>26</ID>
<CNE>16690410</CNE>
<DateofBirth>1997-07-30</DateofBirth>
<FirstName>Mckay</FirstName>
<LastName>Lloyd</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>05 54 62 97 37</Phone>
<Email>rutrum.non.hendrerit@nonenimcommodo.com</Email>
</Student>
<Student>
<ID>27</ID>
<CNE>294038887</CNE>
<DateofBirth>1997-11-24</DateofBirth>
<FirstName>Cline</FirstName>
<LastName>Pratt</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>08 68 14 90 21</Phone>
<Email>scelerisque.neque@sit.ca</Email>
</Student>
<Student>
<ID>28</ID>
<CNE>296273074</CNE>
<DateofBirth>1997-10-03</DateofBirth>
<FirstName>Sutton</FirstName>
<LastName>Sargent</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>08 82 32 18 20</Phone>
<Email>Cras.sed@lobortisquama.org</Email>
</Student>
<Student>
<ID>29</ID>
<CNE>226299332</CNE>
<DateofBirth>1997-08-26</DateofBirth>
<FirstName>Morris</FirstName>
<LastName>Boone</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>07 31 26 49 54</Phone>
<Email>adipiscing@sitamet.com</Email>
</Student>
<Student>
<ID>30</ID>
<CNE>230123094</CNE>
<DateofBirth>1997-11-20</DateofBirth>
<FirstName>Wilkinson</FirstName>
<LastName>Conner</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>07 36 82 96 21</Phone>
<Email>purus@sitamet.com</Email>
</Student>
<Student>
<ID>31</ID>
<CNE>191568658</CNE>
<DateofBirth>1997-05-30</DateofBirth>
<FirstName>Taylor</FirstName>
<LastName>Berg</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>03 45 56 82 04</Phone>
<Email>quis.massa@DonecnibhQuisque.org</Email>
</Student>
<Student>
<ID>32</ID>
<CNE>240621398</CNE>
<DateofBirth>1997-02-20</DateofBirth>
<FirstName>Guy</FirstName>
<LastName>Kim</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>09 62 90 49 19</Phone>
<Email>Donec.tincidunt.Donec@magnaSuspendisse.com</Email>
</Student>
<Student>
<ID>33</ID>
<CNE>221160310</CNE>
<DateofBirth>1997-12-03</DateofBirth>
<FirstName>Savage</FirstName>
<LastName>Barr</LastName>
<ClasseName>GSEA3</ClasseName>
<Phone>01 95 79 01 30</Phone>
<Email>sodales.purus@iaculislacuspede.org</Email>
</Student>
</Students>
