=== Mouadouakil/Students-Marks-System-Xml-Java/STUDENTS/Students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="Students">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Student" minOccurs="1" maxOccurs="unbounded">   
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ID" type="xs:integer"/>
                            <xs:element name="CNE" type="xs:string"/>
                            <xs:element name="DateofBirth" type="xs:date"/>
                            <xs:element name="FirstName" minOccurs="1" maxOccurs="unbounded" >
                              <xs:simpleType>
                                  <xs:restriction base="xs:string">
                                      <xs:pattern value="([a-zA-z])*"/>
                                  </xs:restriction>
                              </xs:simpleType>  
                            </xs:element>
                           
                            <xs:element name="LastName" minOccurs="1" maxOccurs="unbounded">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="([a-zA-z])*"/>
                                    </xs:restriction>
                                </xs:simpleType>  
                            </xs:element>
                            
                            <xs:element name="ClasseName" type="xs:string"/>
                            <xs:element name="Phone" type="xs:string"/>
                            <xs:element name="Email" type="xs:string"/>
                       </xs:sequence>
                        <xs:attribute name="id" type="xs:positiveInteger" use="optional"/>
                    </xs:complexType> 
                </xs:element>
            </xs:sequence>
 
        </xs:complexType>
    </xs:element>   
</xs:schema>

=== Mouadouakil/Students-Marks-System-Xml-Java/STUDENTS/Students_AP2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Students.xsd">
<Student>
<ID>1</ID>
<CNE>16851211</CNE>
<DateofBirth>2002-08-15</DateofBirth>
<FirstName>Lynch</FirstName>
<LastName>Knowles</LastName>
<ClasseName>AP2</ClasseName>
<Phone>01 27 66 52 31</Phone>
<Email>lobortis@eu.com</Email>
</Student>
<Student>
<ID>2</ID>
<CNE>16450123</CNE>
<DateofBirth>2002-06-02</DateofBirth>
<FirstName>Figueroa</FirstName>
<LastName>Gamble</LastName>
<ClasseName>AP2</ClasseName>
<Phone>08 91 85 71 49</Phone>
<Email>ut.dolor.dapibus@felis.net</Email>
</Student>
<Student>
<ID>3</ID>
<CNE>16130611</CNE>
<DateofBirth>2002-03-28</DateofBirth>
<FirstName>Craig</FirstName>
<LastName>Manning</LastName>
<ClasseName>AP2</ClasseName>
<Phone>02 14 98 65 04</Phone>
<Email>magna.Phasellus.dolor@necmetus.co.uk</Email>
</Student>
<Student>
<ID>4</ID>
<CNE>16790103</CNE>
<DateofBirth>2003-01-29</DateofBirth>
<FirstName>Mcdowell</FirstName>
<LastName>Byrd</LastName>
<ClasseName>AP2</ClasseName>
<Phone>02 95 39 28 92</Phone>
<Email>ipsum.ac.mi@dictum.co.uk</Email>
</Student>
<Student>
<ID>5</ID>
<CNE>16630215</CNE>
<DateofBirth>2002-10-10</DateofBirth>
<FirstName>Whitfield</FirstName>
<LastName>Woods</LastName>
<ClasseName>AP2</ClasseName>
<Phone>07 02 34 94 07</Phone>
<Email>dolor@lacinia.edu</Email>
</Student>
<Student>
<ID>6</ID>
<CNE>16950312</CNE>
<DateofBirth>2002-10-04</DateofBirth>
<FirstName>Colon</FirstName>
<LastName>Hartman</LastName>
<ClasseName>AP2</ClasseName>
<Phone>07 57 66 35 57</Phone>
<Email>nec.imperdiet.nec@arcuVestibulum.co.uk</Email>
</Student>
<Student>
<ID>7</ID>
<CNE>16990928</CNE>
<DateofBirth>2002-04-19</DateofBirth>
<FirstName>Sweeney</FirstName>
<LastName>Whitley</LastName>
<ClasseName>AP2</ClasseName>
<Phone>07 52 66 87 75</Phone>
<Email>nulla.vulputate@auctornuncnulla.net</Email>
</Student>
<Student>
<ID>8</ID>
<CNE>16430126</CNE>
<DateofBirth>2002-12-02</DateofBirth>
<FirstName>Dickson</FirstName>
<LastName>Cantrell</LastName>
<ClasseName>AP2</ClasseName>
<Phone>06 99 77 92 63</Phone>
<Email>Sed.molestie.Sed@sodalesnisimagna.com</Email>
</Student>
<Student>
<ID>9</ID>
<CNE>16510530</CNE>
<DateofBirth>2002-12-02</DateofBirth>
<FirstName>Johnson</FirstName>
<LastName>Kerr</LastName>
<ClasseName>AP2</ClasseName>
<Phone>07 36 84 75 89</Phone>
<Email>ultrices@nequeNullam.net</Email>
</Student>
<Student>
<ID>10</ID>
<CNE>16701206</CNE>
<DateofBirth>2002-09-25</DateofBirth>
<FirstName>Mcdowell</FirstName>
<LastName>Mccullough</LastName>
<ClasseName>AP2</ClasseName>
<Phone>04 66 70 93 99</Phone>
<Email>pede.ultrices@dictummi.com</Email>
</Student>
<Student>
<ID>11</ID>
<CNE>16160104</CNE>
<DateofBirth>2002-06-27</DateofBirth>
<FirstName>Tyson</FirstName>
<LastName>Mcintosh</LastName>
<ClasseName>AP2</ClasseName>
<Phone>07 89 99 82 58</Phone>
<Email>magna@accumsan.org</Email>
</Student>
<Student>
<ID>12</ID>
<CNE>16201127</CNE>
<DateofBirth>2002-08-20</DateofBirth>
<FirstName>Rose</FirstName>
<LastName>Villarreal</LastName>
<ClasseName>AP2</ClasseName>
<Phone>03 96 26 81 26</Phone>
<Email>orci.adipiscing.non@iaculislacus.org</Email>
</Student>
<Student>
<ID>13</ID>
<CNE>16610508</CNE>
<DateofBirth>2002-10-02</DateofBirth>
<FirstName>Reid</FirstName>
<LastName>Fisher</LastName>
<ClasseName>AP2</ClasseName>
<Phone>08 97 33 21 53</Phone>
<Email>ullamcorper.Duis@Inornare.org</Email>
</Student>
<Student>
<ID>14</ID>
<CNE>16691027</CNE>
<DateofBirth>2002-03-10</DateofBirth>
<FirstName>Glenn</FirstName>
<LastName>Thompson</LastName>
<ClasseName>AP2</ClasseName>
<Phone>07 16 40 37 32</Phone>
<Email>sit@Nullam.ca</Email>
</Student>
<Student>
<ID>15</ID>
<CNE>16500302</CNE>
<DateofBirth>2002-05-24</DateofBirth>
<FirstName>Gutierrez</FirstName>
<LastName>Coleman</LastName>
<ClasseName>AP2</ClasseName>
<Phone>02 02 85 10 47</Phone>
<Email>nonummy@orcitincidunt.ca</Email>
</Student>
<Student>
<ID>16</ID>
<CNE>16080714</CNE>
<DateofBirth>2002-07-12</DateofBirth>
<FirstName>Duncan</FirstName>
<LastName>Chambers</LastName>
<ClasseName>AP2</ClasseName>
<Phone>05 89 65 75 63</Phone>
<Email>eleifend@idlibero.net</Email>
</Student>
<Student>
<ID>17</ID>
<CNE>16910723</CNE>
<DateofBirth>2002-09-10</DateofBirth>
<FirstName>Strong</FirstName>
<LastName>Oconnor</LastName>
<ClasseName>AP2</ClasseName>
<Phone>03 12 31 58 90</Phone>
<Email>libero.Proin@lacuspedesagittis.co.uk</Email>
</Student>
<Student>
<ID>18</ID>
<CNE>16891209</CNE>
<DateofBirth>2002-03-16</DateofBirth>
<FirstName>Langley</FirstName>
<LastName>Mccullough</LastName>
<ClasseName>AP2</ClasseName>
<Phone>07 00 58 04 78</Phone>
<Email>consequat.lectus@porttitorscelerisqueneque.ca</Email>
</Student>
<Student>
<ID>19</ID>
<CNE>16250402</CNE>
<DateofBirth>2002-08-17</DateofBirth>
<FirstName>Durham</FirstName>
<LastName>Vaughan</LastName>
<ClasseName>AP2</ClasseName>
<Phone>03 06 37 96 17</Phone>
<Email>Donec@ipsum.co.uk</Email>
</Student>
<Student>
<ID>20</ID>
<CNE>16970209</CNE>
<DateofBirth>2002-12-01</DateofBirth>
<FirstName>Perry</FirstName>
<LastName>Levy</LastName>
<ClasseName>AP2</ClasseName>
<Phone>03 75 31 08 21</Phone>
<Email>nulla.Integer.urna@quis.org</Email>
</Student>
<Student>
<ID>21</ID>
<CNE>16660206</CNE>
<DateofBirth>2002-03-14</DateofBirth>
<FirstName>Lawrence</FirstName>
<LastName>Espinoza</LastName>
<ClasseName>AP2</ClasseName>
<Phone>09 30 21 59 83</Phone>
<Email>at@nuncnulla.net</Email>
</Student>
<Student>
<ID>22</ID>
<CNE>16930503</CNE>
<DateofBirth>2002-07-30</DateofBirth>
<FirstName>Freeman</FirstName>
<LastName>Vaughn</LastName>
<ClasseName>AP2</ClasseName>
<Phone>02 68 34 47 98</Phone>
<Email>Suspendisse@amet.co.uk</Email>
</Student>
<Student>
<ID>23</ID>
<CNE>16220706</CNE>
<DateofBirth>2002-11-29</DateofBirth>
<FirstName>Torres</FirstName>
<LastName>Parsons</LastName>
<ClasseName>AP2</ClasseName>
<Phone>04 47 92 51 70</Phone>
<Email>lobortis.tellus.justo@vel.com</Email>
</Student>
<Student>
<ID>24</ID>
<CNE>16590413</CNE>
<DateofBirth>2002-09-27</DateofBirth>
<FirstName>Gilbert</FirstName>
<LastName>Owen</LastName>
<ClasseName>AP2</ClasseName>
<Phone>04 73 34 12 35</Phone>
<Email>sagittis.lobortis@egestasDuis.co.uk</Email>
</Student>
<Student>
<ID>25</ID>
<CNE>16161018</CNE>
<DateofBirth>2002-08-05</DateofBirth>
<FirstName>Hodge</FirstName>
<LastName>Grant</LastName>
<ClasseName>AP2</ClasseName>
<Phone>04 89 81 94 11</Phone>
<Email>tempor@luctus.org</Email>
</Student>
<Student>
<ID>26</ID>
<CNE>16740317</CNE>
<DateofBirth>2002-10-04</DateofBirth>
<FirstName>Gibbs</FirstName>
<LastName>Parrish</LastName>
<ClasseName>AP2</ClasseName>
<Phone>07 13 43 96 72</Phone>
<Email>hendrerit@Donecfelisorci.com</Email>
</Student>
<Student>
<ID>27</ID>
<CNE>16421018</CNE>
<DateofBirth>2002-04-29</DateofBirth>
<FirstName>Hurst</FirstName>
<LastName>Alford</LastName>
<ClasseName>AP2</ClasseName>
<Phone>07 94 27 18 37</Phone>
<Email>semper.pretium.neque@Maurisquis.org</Email>
</Student>
<Student>
<ID>28</ID>
<CNE>16671008</CNE>
<DateofBirth>2002-06-11</DateofBirth>
<FirstName>Robertson</FirstName>
<LastName>Blake</LastName>
<ClasseName>AP2</ClasseName>
<Phone>09 39 17 51 30</Phone>
<Email>pede.Nunc.sed@magnaSuspendisse.edu</Email>
</Student>
<Student>
<ID>29</ID>
<CNE>16160813</CNE>
<DateofBirth>2002-07-07</DateofBirth>
<FirstName>George</FirstName>
<LastName>Harris</LastName>
<ClasseName>AP2</ClasseName>
<Phone>08 29 04 82 88</Phone>
<Email>euismod.enim.Etiam@eunibh.edu</Email>
</Student>
<Student>
<ID>30</ID>
<CNE>16860418</CNE>
<DateofBirth>2002-09-19</DateofBirth>
<FirstName>Mcpherson</FirstName>
<LastName>Cruz</LastName>
<ClasseName>AP2</ClasseName>
<Phone>04 44 63 23 62</Phone>
<Email>est@Aliquam.co.uk</Email>
</Student>
<Student>
<ID>31</ID>
<CNE>16270530</CNE>
<DateofBirth>2002-10-13</DateofBirth>
<FirstName>Calderon</FirstName>
<LastName>Whitehead</LastName>
<ClasseName>AP2</ClasseName>
<Phone>08 63 40 26 88</Phone>
<Email>Morbi.accumsan@nibh.edu</Email>
</Student>
<Student>
<ID>32</ID>
<CNE>16400221</CNE>
<DateofBirth>2002-08-15</DateofBirth>
<FirstName>Tyler</FirstName>
<LastName>Castillo</LastName>
<ClasseName>AP2</ClasseName>
<Phone>05 22 72 00 78</Phone>
<Email>arcu.Vestibulum.ante@pretiumnequeMorbi.net</Email>
</Student>
</Students>

=== Mouadouakil/Students-Marks-System-Xml-Java/STUDENTS/Students_GSTR3.xml
<?xml version="1.0" encoding="UTF-8"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Students.xsd">
<Student>
<ID>1</ID>
<CNE>288053062</CNE>
<DateofBirth>1997-10-09</DateofBirth>
<FirstName>Wells</FirstName>
<LastName>Garrett</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>05 91 84 06 44</Phone>
<Email>metus@In.edu</Email>
</Student>
<Student>
<ID>2</ID>
<CNE>235940312</CNE>
<DateofBirth>1997-07-11</DateofBirth>
<FirstName>Leach</FirstName>
<LastName>Hyde</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>08 75 35 29 74</Phone>
<Email>Duis.dignissim@luctus.com</Email>
</Student>
<Student>
<ID>3</ID>
<CNE>294585441</CNE>
<DateofBirth>1997-07-28</DateofBirth>
<FirstName>Phillips</FirstName>
<LastName>Gordon</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>04 26 43 30 27</Phone>
<Email>Praesent@velpedeblandit.net</Email>
</Student>
<Student>
<ID>4</ID>
<CNE>185463291</CNE>
<DateofBirth>1997-09-22</DateofBirth>
<FirstName>Delgado</FirstName>
<LastName>Banks</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>07 61 63 29 18</Phone>
<Email>non@ut.com</Email>
</Student>
<Student>
<ID>5</ID>
<CNE>278500645</CNE>
<DateofBirth>1997-02-11</DateofBirth>
<FirstName>Garner</FirstName>
<LastName>Coleman</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>02 93 41 19 74</Phone>
<Email>bibendum.ullamcorper.Duis@enimSuspendisse.net</Email>
</Student>
<Student>
<ID>6</ID>
<CNE>246813080</CNE>
<DateofBirth>1997-02-28</DateofBirth>
<FirstName>Miles</FirstName>
<LastName>Avila</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>05 63 85 99 02</Phone>
<Email>et@adipiscing.org</Email>
</Student>
<Student>
<ID>7</ID>
<CNE>227348823</CNE>
<DateofBirth>1997-06-15</DateofBirth>
<FirstName>Lamb</FirstName>
<LastName>Moreno</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>05 45 89 38 81</Phone>
<Email>id.erat.Etiam@odiosemper.co.uk</Email>
</Student>
<Student>
<ID>8</ID>
<CNE>221356590</CNE>
<DateofBirth>1997-09-14</DateofBirth>
<FirstName>Moon</FirstName>
<LastName>Dale</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>02 87 26 62 06</Phone>
<Email>Nunc.sed@Crasinterdum.net</Email>
</Student>
<Student>
<ID>9</ID>
<CNE>294038887</CNE>
<DateofBirth>1997-10-06</DateofBirth>
<FirstName>Alston</FirstName>
<LastName>Patel</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>03 48 72 12 70</Phone>
<Email>magna@consectetuermauris.net</Email>
</Student>
<Student>
<ID>10</ID>
<CNE>296273074</CNE>
<DateofBirth>1997-03-31</DateofBirth>
<FirstName>Hinton</FirstName>
<LastName>Howe</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>07 48 68 51 07</Phone>
<Email>tempus.risus.Donec@nequeIn.edu</Email>
</Student>
<Student>
<ID>11</ID>
<CNE>226299332</CNE>
<DateofBirth>1997-06-29</DateofBirth>
<FirstName>Stevenson</FirstName>
<LastName>Gallegos</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>02 30 15 23 24</Phone>
<Email>aliquam@vitae.ca</Email>
</Student>
<Student>
<ID>12</ID>
<CNE>230123094</CNE>
<DateofBirth>1997-01-12</DateofBirth>
<FirstName>Acosta</FirstName>
<LastName>Tyler</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>06 57 56 28 00</Phone>
<Email>blandit@tinciduntnuncac.org</Email>
</Student>
<Student>
<ID>13</ID>
<CNE>191568658</CNE>
<DateofBirth>1997-02-03</DateofBirth>
<FirstName>Gibbs</FirstName>
<LastName>Prince</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>04 66 25 76 96</Phone>
<Email>pretium.neque@cursusnon.com</Email>
</Student>
<Student>
<ID>14</ID>
<CNE>240621398</CNE>
<DateofBirth>1997-02-18</DateofBirth>
<FirstName>Blair</FirstName>
<LastName>Langley</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>07 17 90 46 69</Phone>
<Email>libero.et@vitae.edu</Email>
</Student>
<Student>
<ID>15</ID>
<CNE>221160310</CNE>
<DateofBirth>1997-01-21</DateofBirth>
<FirstName>Estrada</FirstName>
<LastName>Hood</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>07 22 52 54 25</Phone>
<Email>feugiat.metus@etarcuimperdiet.ca</Email>
</Student>
<Student>
<ID>16</ID>
<CNE>296887694</CNE>
<DateofBirth>1997-09-03</DateofBirth>
<FirstName>Stewart</FirstName>
<LastName>Cameron</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>04 32 29 44 08</Phone>
<Email>euismod.mauris@nequeMorbi.net</Email>
</Student>
<Student>
<ID>17</ID>
<CNE>271963461</CNE>
<DateofBirth>1997-06-20</DateofBirth>
<FirstName>Rose</FirstName>
<LastName>Russo</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>05 73 84 78 34</Phone>
<Email>ridiculus.mus@purusDuiselementum.ca</Email>
</Student>
<Student>
<ID>18</ID>
<CNE>185162486</CNE>
<DateofBirth>1997-07-05</DateofBirth>
<FirstName>Norman</FirstName>
<LastName>Hood</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>03 48 55 39 48</Phone>
<Email>aliquam.eros@ligulaconsectetuer.org</Email>
</Student>
<Student>
<ID>19</ID>
<CNE>209255448</CNE>
<DateofBirth>1997-10-31</DateofBirth>
<FirstName>Carter</FirstName>
<LastName>Peterson</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>08 71 41 24 42</Phone>
<Email>ipsum@lobortis.com</Email>
</Student>
<Student>
<ID>20</ID>
<CNE>194910614</CNE>
<DateofBirth>1997-09-11</DateofBirth>
<FirstName>Dale</FirstName>
<LastName>Soto</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>08 76 82 32 58</Phone>
<Email>molestie.tellus.Aenean@milaciniamattis.edu</Email>
</Student>
<Student>
<ID>21</ID>
<CNE>189353425</CNE>
<DateofBirth>1997-04-21</DateofBirth>
<FirstName>Woodard</FirstName>
<LastName>Mcdowell</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>05 11 02 49 12</Phone>
<Email>pretium.et@lacusQuisque.co.uk</Email>
</Student>
<Student>
<ID>22</ID>
<CNE>184360315</CNE>
<DateofBirth>1997-01-07</DateofBirth>
<FirstName>Morales</FirstName>
<LastName>Russo</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>01 61 64 37 87</Phone>
<Email>ut.pellentesque@necquam.co.uk</Email>
</Student>
<Student>
<ID>23</ID>
<CNE>218118187</CNE>
<DateofBirth>1997-09-21</DateofBirth>
<FirstName>Davenport</FirstName>
<LastName>Le</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>07 96 02 79 89</Phone>
<Email>tempor@etlaciniavitae.ca</Email>
</Student>
<Student>
<ID>24</ID>
<CNE>228759693</CNE>
<DateofBirth>1997-07-17</DateofBirth>
<FirstName>Best</FirstName>
<LastName>Holden</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>07 99 96 77 89</Phone>
<Email>auctor.vitae@sit.org</Email>
</Student>
<Student>
<ID>25</ID>
<CNE>217009019</CNE>
<DateofBirth>1997-03-19</DateofBirth>
<FirstName>Barr</FirstName>
<LastName>Foster</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>04 16 45 62 49</Phone>
<Email>iaculis.lacus@nislQuisque.ca</Email>
</Student>
<Student>
<ID>26</ID>
<CNE>253172430</CNE>
<DateofBirth>1997-07-30</DateofBirth>
<FirstName>Rivera</FirstName>
<LastName>Warren</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>07 84 90 26 55</Phone>
<Email>tristique@etmagnaPraesent.net</Email>
</Student>
<Student>
<ID>27</ID>
<CNE>270185581</CNE>
<DateofBirth>1997-11-24</DateofBirth>
<FirstName>Davenport</FirstName>
<LastName>Todd</LastName>
<ClasseName>GSTR3</ClasseName>
<Phone>09 60 70 45 51</Phone>
<Email>in@eratVivamusnisi.org</Email>
</Student>
</Students>

=== Mouadouakil/Students-Marks-System-Xml-Java/STUDENTS/Students_G3EI2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Students.xsd">
<Student>
<ID>1</ID>
<CNE>371389830</CNE>
<DateofBirth>1998-04-28</DateofBirth>
<FirstName>Mcknight</FirstName>
<LastName>Rodgers</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>01 60 02 69 66</Phone>
<Email>ligula@utlacus.com</Email>
</Student>
<Student>
<ID>2</ID>
<CNE>348290556</CNE>
<DateofBirth>1998-02-14</DateofBirth>
<FirstName>Wise</FirstName>
<LastName>Neal</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>01 47 61 63 20</Phone>
<Email>consectetuer.cursus.et@tellus.net</Email>
</Student>
<Student>
<ID>3</ID>
<CNE>321331598</CNE>
<DateofBirth>1998-10-05</DateofBirth>
<FirstName>Wise</FirstName>
<LastName>Slater</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>07 28 41 20 85</Phone>
<Email>iaculis.quis.pede@Curabitur.co.uk</Email>
</Student>
<Student>
<ID>4</ID>
<CNE>250033501</CNE>
<DateofBirth>1998-06-26</DateofBirth>
<FirstName>Berry</FirstName>
<LastName>Brooks</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>01 35 91 59 98</Phone>
<Email>imperdiet@vulputateveliteu.edu</Email>
</Student>
<Student>
<ID>5</ID>
<CNE>200836891</CNE>
<DateofBirth>1998-02-05</DateofBirth>
<FirstName>Hatfield</FirstName>
<LastName>Hopkins</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>03 60 79 04 32</Phone>
<Email>molestie.arcu.Sed@semper.com</Email>
</Student>
<Student>
<ID>6</ID>
<CNE>296306314</CNE>
<DateofBirth>1998-05-19</DateofBirth>
<FirstName>Bryan</FirstName>
<LastName>Finley</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>05 04 84 20 22</Phone>
<Email>tincidunt.nibh.Phasellus@mauris.org</Email>
</Student>
<Student>
<ID>7</ID>
<CNE>234091048</CNE>
<DateofBirth>1998-04-06</DateofBirth>
<FirstName>Chavez</FirstName>
<LastName>Adkins</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>05 59 55 42 23</Phone>
<Email>tempor@nuncnullavulputate.edu</Email>
</Student>
<Student>
<ID>8</ID>
<CNE>202105242</CNE>
<DateofBirth>1998-03-04</DateofBirth>
<FirstName>Summers</FirstName>
<LastName>Dorsey</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>02 08 19 95 43</Phone>
<Email>mauris.Integer@vellectus.co.uk</Email>
</Student>
<Student>
<ID>9</ID>
<CNE>312006938</CNE>
<DateofBirth>1998-03-16</DateofBirth>
<FirstName>Cline</FirstName>
<LastName>Sandoval</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>01 52 65 49 31</Phone>
<Email>rutrum.justo.Praesent@enim.net</Email>
</Student>
<Student>
<ID>10</ID>
<CNE>394623604</CNE>
<DateofBirth>1998-05-21</DateofBirth>
<FirstName>Flores</FirstName>
<LastName>Terrell</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>05 76 26 69 13</Phone>
<Email>ipsum.sodales.purus@velfaucibusid.com</Email>
</Student>
<Student>
<ID>11</ID>
<CNE>279070875</CNE>
<DateofBirth>1998-11-02</DateofBirth>
<FirstName>Singleton</FirstName>
<LastName>Morgan</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>05 13 35 75 80</Phone>
<Email>gravida.molestie@placerat.co.uk</Email>
</Student>
<Student>
<ID>12</ID>
<CNE>331208967</CNE>
<DateofBirth>1998-08-14</DateofBirth>
<FirstName>Mccall</FirstName>
<LastName>Mosley</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>06 67 67 30 85</Phone>
<Email>ac.orci@Nullasemper.org</Email>
</Student>
<Student>
<ID>13</ID>
<CNE>328593126</CNE>
<DateofBirth>1998-08-23</DateofBirth>
<FirstName>David</FirstName>
<LastName>Cervantes</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>05 51 65 19 26</Phone>
<Email>blandit.enim.consequat@velitjustonec.com</Email>
</Student>
<Student>
<ID>14</ID>
<CNE>396076748</CNE>
<DateofBirth>1998-03-15</DateofBirth>
<FirstName>Hutchinson</FirstName>
<LastName>Hicks</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>06 18 00 52 59</Phone>
<Email>dictum.augue.malesuada@aliquetsem.com</Email>
</Student>
<Student>
<ID>15</ID>
<CNE>245788572</CNE>
<DateofBirth>1998-03-28</DateofBirth>
<FirstName>Santos</FirstName>
<LastName>Alford</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>04 20 50 00 97</Phone>
<Email>tempus@Phasellusat.org</Email>
</Student>
<Student>
<ID>16</ID>
<CNE>294409700</CNE>
<DateofBirth>1998-10-24</DateofBirth>
<FirstName>Glover</FirstName>
<LastName>Wilson</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>05 74 54 21 69</Phone>
<Email>amet.risus.Donec@maurisSuspendisse.ca</Email>
</Student>
<Student>
<ID>17</ID>
<CNE>391261235</CNE>
<DateofBirth>1998-09-18</DateofBirth>
<FirstName>Fischer</FirstName>
<LastName>Kennedy</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>01 41 85 29 14</Phone>
<Email>mi.lacinia@scelerisque.co.uk</Email>
</Student>
<Student>
<ID>18</ID>
<CNE>194440161</CNE>
<DateofBirth>1998-09-25</DateofBirth>
<FirstName>Ballard</FirstName>
<LastName>Savage</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>06 25 03 23 71</Phone>
<Email>lacinia.vitae.sodales@elitAliquamauctor.org</Email>
</Student>
<Student>
<ID>19</ID>
<CNE>209480800</CNE>
<DateofBirth>1998-07-12</DateofBirth>
<FirstName>Tyson</FirstName>
<LastName>Patel</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>07 61 85 24 74</Phone>
<Email>eros.Proin.ultrices@odioPhasellusat.net</Email>
</Student>
<Student>
<ID>20</ID>
<CNE>292595643</CNE>
<DateofBirth>1998-08-14</DateofBirth>
<FirstName>Weaver</FirstName>
<LastName>Berger</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>01 53 72 38 38</Phone>
<Email>molestie.pharetra@adipiscingelitEtiam.com</Email>
</Student>
<Student>
<ID>21</ID>
<CNE>212109963</CNE>
<DateofBirth>1998-08-18</DateofBirth>
<FirstName>Griffin</FirstName>
<LastName>Cotton</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>02 71 67 66 06</Phone>
<Email>Cras.convallis@Sednullaante.net</Email>
</Student>
<Student>
<ID>22</ID>
<CNE>312111967</CNE>
<DateofBirth>1998-10-14</DateofBirth>
<FirstName>Case</FirstName>
<LastName>Keller</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>02 98 00 39 62</Phone>
<Email>molestie@posuere.org</Email>
</Student>
<Student>
<ID>23</ID>
<CNE>190672409</CNE>
<DateofBirth>1998-12-31</DateofBirth>
<FirstName>Eaton</FirstName>
<LastName>Fowler</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>07 34 75 05 65</Phone>
<Email>cursus.et@inceptoshymenaeos.com</Email>
</Student>
<Student>
<ID>24</ID>
<CNE>240451161</CNE>
<DateofBirth>1998-12-27</DateofBirth>
<FirstName>Roberson</FirstName>
<LastName>Molina</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>06 70 78 09 47</Phone>
<Email>Donec.egestas.Duis@liberoDonec.ca</Email>
</Student>
<Student>
<ID>25</ID>
<CNE>358488890</CNE>
<DateofBirth>1998-11-18</DateofBirth>
<FirstName>Bonner</FirstName>
<LastName>Briggs</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>08 26 88 28 87</Phone>
<Email>quam@malesuada.com</Email>
</Student>
<Student>
<ID>26</ID>
<CNE>375569446</CNE>
<DateofBirth>1998-03-03</DateofBirth>
<FirstName>Summers</FirstName>
<LastName>Mccray</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>04 15 83 58 89</Phone>
<Email>convallis.est@tempusnon.com</Email>
</Student>
<Student>
<ID>27</ID>
<CNE>260617309</CNE>
<DateofBirth>1998-12-24</DateofBirth>
<FirstName>Schwartz</FirstName>
<LastName>Hickman</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>01 84 72 63 22</Phone>
<Email>tristique@lobortis.edu</Email>
</Student>
<Student>
<ID>28</ID>
<CNE>392304192</CNE>
<DateofBirth>1998-02-03</DateofBirth>
<FirstName>Oneil</FirstName>
<LastName>Richardson</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>01 61 10 62 63</Phone>
<Email>ipsum.Suspendisse@sitametante.org</Email>
</Student>
<Student>
<ID>29</ID>
<CNE>318503192</CNE>
<DateofBirth>1998-07-11</DateofBirth>
<FirstName>Monroe</FirstName>
<LastName>Swanson</LastName>
<ClasseName>G3EI2</ClasseName>
<Phone>06 74 50 68 89</Phone>
<Email>mi.felis.adipiscing@nisl.ca</Email>
</Student>
</Students>
